networks:
  web-network:


services:
  water:
    build:
      context: ./docker/images/water
    container_name: water
    restart: "no"
    tty: true
    depends_on:
      - beanstalkd
      - mariadb
      - redis
      - feapp
    volumes:
      - ./docker/images/water/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/images/water/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/images/water/nginx/sites:/etc/nginx/sites
      - ./docker/images/water/supervisor.d:/etc/supervisor.d
      - ./docker/images/water/php:/etc/php
      - /etc/letsencrypt:/etc/letsencrypt
      - ./codebases:/var/www
    ports:
      - "80:80"
      - "443:443"
    networks:
      web-network:
        aliases:
          - ${BE_URL}
          - ${FE_URL}

  feapp:
    build:
      context: ./codebases/trustwaiver-fe
    container_name: feapp
    tty: true
    volumes:
      - ./codebases:/var/www/
    working_dir: /var/www/trustwaiver-fe
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      web-network:


  mariadb:
    build:
      context: ./docker/images/mariadb
    container_name: mariadb
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./docker/images/mariadb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      web-network:


  redis:
    build:
      context: ./docker/images/redis
    container_name: redis
    tty: true
    ports:
      - "6379:6379"
    networks:
      web-network:


  beanstalkd:
    image: schickling/beanstalkd
    container_name: beanstalkd
    ports:
      - "11300:11300"
